version: '3'

services:
  repeater:
    image: deweiliu/dewei-webpage-repeater:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    container_name: dewei-webpage-repeater-container