name: Docker Compose CI

on: [push]

jobs:
  build-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Build and upload Docker image
        run: |
          # variables
          current_time=$(date +%s)
          docker_username=deweiliu
          docker_password=${{ secrets.docker_access }}

          # execute
          docker-compose build --build-arg build_time=${current_time}
          docker login --username ${docker_username} --password ${docker_password}
          docker-compose push
          docker logout

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update App service on Azure
        run: |
          # variables
          webapp_name=webpage-repeater
          resource_group=app-services

          # execute
          az webapp restart --name ${webapp_name} --resource-group ${resource_group}

      - name: Logout Azure
        run: |
          az logout
