name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag deweiliu/searching:latest
        docker login --username deweiliu --password ${{ secrets.docker_access }}
        docker push deweiliu/searching:latest
        docker logout