name: Docker Compose CI

on: [push]

jobs:

  build-update:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v1

    - name: Build the Docker image
      run: |
        current_time=$(date +%s)
        docker-compose build --build-arg build_time=${current_time}
        docker login --username deweiliu --password ${{ secrets.docker_access }}
        docker-compose push
        docker logout

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update App service on Azure
      run: |
        az webapp restart --name webpage-repeater --resource-group app-services 