name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        current_time=$(date +%s)
        docker build . --file Dockerfile --tag deweiliu/dewei-webpage-repeater:latest --build-arg build_time=${current_time}
        docker login --username deweiliu --password ${{ secrets.docker_access }}
        docker push deweiliu/dewei-webpage-repeater:latest
        docker logout